"""create post table

Revision ID: 7cc729f13292
Revises: 
Create Date: 2025-02-03 13:49:42.920359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc729f13292'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('like', sa.Integer(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_posts_pk'), 'posts', ['pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_pk'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
