"""add version field

Revision ID: 8b4638468e7f
Revises: 7cc729f13292
Create Date: 2025-02-03 16:10:19.349546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b4638468e7f'
down_revision: Union[str, None] = '7cc729f13292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('version', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'version')
    # ### end Alembic commands ###
